name: Build LaTeX document

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex

      - name: Upload a build artifact
        uses: actions/upload-artifact@v4
        with:
          name: building-derivations
          path: main.pdf